name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint
