name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Install
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Prepare
        run: npm run publish:prepare
        
      - name: Publish
        run: npm publish --access public
        working-directory: dist/ngx-development-kit
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
        
        
