name: Testing

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: actions/checkout@v3.3.0

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --no-watch --code-coverage
