name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test:ci
